import React from 'react'
import DashboardLayout from '../components/DashboardLayout'
import MatchCard from '../components/MatchCard'
import { Brain, Cpu, Database, CpuIcon, Layers, Network } from 'lucide-react'

export default function About() {
  const pipelineSteps = [
    {
      icon: Database,
      title: "Document Ingestion",
      desc: "Takes PDF/DOCX resumes, normalizes the layout structure, and strips boilerplate code, formatting, and unicode characters using PyMuPDF and python-docx."
    },
    {
      icon: Network,
      title: "Sentence Transformer",
      desc: "Translates the cleaned resume text into a 384-dimensional dense semantic vector space utilizing the pretrained HuggingFace sentence-transformers/all-MiniLM-L6-v2 model."
    },
    {
      icon: Brain,
      title: "Feed-Forward ANN",
      desc: "Applies a trained 3-layer neural network (384 input features -> 256 dense ReLU -> 128 dense ReLU -> 25 class softmax probabilities) to compute domain alignments."
    }
  ]

  return (
    <DashboardLayout>
      {/* Header Info */}
      <div className="mb-10">
        <span className="text-xs uppercase font-bold tracking-widest text-accent font-mono block mb-1">
          Model Specifications
        </span>
        <h1 className="text-3xl font-extrabold text-white mb-2 font-sans tracking-tight">
          About Resume AI
        </h1>
        <p className="text-sm text-white/50">
          Under the hood of our neural-semantic matching engine.
        </p>
      </div>

      <div className="flex flex-col gap-8">
        
        {/* Core details */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {pipelineSteps.map((step, idx) => {
            const Icon = step.icon
            return (
              <MatchCard key={idx} hoverGlow={true}>
                <div className="w-12 h-12 rounded-xl bg-black border border-white/5 flex items-center justify-center mb-4">
                  <Icon className="w-5 h-5 text-accent" />
                </div>
                <h3 className="text-lg font-bold text-white mb-2 font-sans">{step.title}</h3>
                <p className="text-xs text-white/50 leading-relaxed">{step.desc}</p>
              </MatchCard>
            )
          })}
        </div>

        {/* Model info block */}
        <MatchCard hoverGlow={false} className="p-8">
          <h2 className="text-xl font-bold text-white mb-4 font-sans">
            Neural Classifier Architecture
          </h2>
          <p className="text-sm text-white/60 mb-6 leading-relaxed">
            Our neural classification layer is custom-trained to predict career domains across 25 distinct professional domains. It maps the 384-dimensional dense semantic embeddings generated by the Transformer into a categorical probability distribution.
          </p>

          {/* Model Summary Table */}
          <div className="w-full bg-black/40 border border-white/5 rounded-xl overflow-hidden text-xs font-mono">
            <div className="grid grid-cols-3 p-3.5 border-b border-white/5 font-bold text-white/40 bg-white/[0.01]">
              <div>Layer (type)</div>
              <div>Output Shape</div>
              <div>Param #</div>
            </div>
            
            <div className="grid grid-cols-3 p-3.5 border-b border-white/5 text-white/80">
              <div className="font-semibold text-accent">dense (Dense)</div>
              <div>(None, 256)</div>
              <div>98,560</div>
            </div>

            <div className="grid grid-cols-3 p-3.5 border-b border-white/5 text-white/80">
              <div className="font-semibold text-accent">dense_1 (Dense)</div>
              <div>(None, 128)</div>
              <div>32,896</div>
            </div>

            <div className="grid grid-cols-3 p-3.5 text-white/80">
              <div className="font-semibold text-accent">dense_2 (Dense)</div>
              <div>(None, 25)</div>
              <div>3,225</div>
            </div>

            <div className="grid grid-cols-3 p-3.5 border-t border-white/5 font-bold text-white bg-white/[0.01]">
              <div>Total Parameters</div>
              <div>-</div>
              <div>134,681</div>
            </div>
          </div>
        </MatchCard>
      </div>
    </DashboardLayout>
  )
}
